"use strict";
var emoticons = [
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM7a38SyvibMdKu7QdRnzA2DNgFxOmscPV8wXsq5yPPuKS6Y7h6WaqrUj/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLCmxPqI7fND1qGONxNFUlYFOjU4KgibMoW7QhNHvGgvSxTaia3vIGibgcb/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLALxSLBT9ia2YCSr91OQlHlEiad2t2GicJord47ib67Mxc3auY88KxxYfaQ/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLDOlsGtttOfyF6vl8PfTSX3TJldR1Wuv2RAf3q1K5Nn7j7WQ5hXgml9/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM5UsScDOdkHGJNRP5yDrckzsoibkVBlDrQqmib3cy2l4Cu3ibb60AJPeiae/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLBG3Rhvyaot4IScv6JFjxlVCAKjR8gYdxX1MmjiaMozztJy3L1x3xwZe/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLBVWrxFJdiaibzgv70oTHNTwV4ia9rbthU9A9yyflGX5vqvJAcvibSIOfn4/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLA8JYkwicuPa1DO7qthyXkxHfhWMBtwPMXmEnMWbuhkZuiazuuSfia8q7R/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLA5Maia2pqHavS9S467uLOT9Q3jial0Ngdu7x9ICPzFOLC5Wew2e4RrfU/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLDmvO21MHeS1VTgS1LUFEJHqibOMiaO9DtQruibJAbPE5CO3cicY907SWIU/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLCSGzU8cqeRmPB0EBoEic4eHhVAia1zTictm183odyByibmKQgUOyXoSNBI/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLAhXBBjIqSl2SgBv4jJm9M18b1HxqJITJ3WBlo4TtLpIfcvmdhh1Snj/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLA0S5KxD3YJjSsrFTibC2WpWkZM1A770TcibhibAictCTcKX6KZEeICdk4v/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLCdwOLyl7c6JL2MicjB54Byicf9PM3ic3bzUaslicysDLhKFpXSvuG1dfw2/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM4fgQ41VTF2rFuy2AYNWPuFnkTLWiayL7Jt9jaibq6ChMahB6LpURwlKK/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM7lf1vRwFDtwKvniaPib1au1P5ib4LDkkXbXicfT4kpAtH9MD3uQAHu1Bnw/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM7ODaqSxITnwsEpicghhK56TM9ZibqNPsVCQPYCoicicWGDzvRRvnNZj5wh/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLBpI7y0C4mp9rVIfDl46zAtwhXslwKsMW6YrPkkmqOsJrpoJOCU5dN7/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLCDicxCiafP2KpoQPg26rCqFyLMWWvkI3ASqpNNalBKSRWQI8d9DOVSPR/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM6n8rbxOAOExMmDGvm0VOQp9eeiczPTNpJYYYR9q2ooJBeiasDeEIKBB9/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM5iawwfTzpjEzPNlcnL3fnTjpHic8uXiaRwOWfica6NDPd24pSkdy3f7Wuia/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLAqn9uGg0riawRB0kRapu7yCzYSShsHplGmBoj3ibNS0fP9pxPvlqVWM2/0",
    "http://mmbiz.qpic.cn/mmemoticon/Q3auHgzwzM5GInBY3yWKjicpnkMDY78NC72BibvyicltAUqoXLOr4xSarjquEvoHIJ7/0",
    "http://mmbiz.qpic.cn/mmemoticon/ajNVdqHZLLACNZkcWvHBNYicSCBu9Hg7sq3cuw9o6aQ2UeDqrNS0G55tOgFUeWic3Q/0",
];
//# sourceMappingURL=emoticons.js.map